"""Integration platform for recorder."""
from __future__ import annotations

from homeassistant.components.vacuum import ATTR_BATTERY_ICON
from homeassistant.core import HomeAssistant, callback

from .const import (
    ATTRIBUTE_CALIBRATION,
    ATTRIBUTE_CARPET_MAP,
    ATTRIBUTE_CHARGER,
    ATTRIBUTE_CLEANED_ROOMS,
    ATTRIBUTE_GOTO,
    ATTRIBUTE_GOTO_PATH,
    ATTRIBUTE_GOTO_PREDICTED_PATH,
    ATTRIBUTE_IGNORED_OBSTACLES,
    ATTRIBUTE_IGNORED_OBSTACLES_WITH_PHOTO,
    ATTRIBUTE_IMAGE,
    ATTRIBUTE_IS_EMPTY,
    ATTRIBUTE_MAP_NAME,
    ATTRIBUTE_MOP_PATH,
    ATTRIBUTE_NO_CARPET_AREAS,
    ATTRIBUTE_NO_GO_AREAS,
    ATTRIBUTE_NO_MOPPING_AREAS,
    ATTRIBUTE_OBSTACLES,
    ATTRIBUTE_OBSTACLES_WITH_PHOTO,
    ATTRIBUTE_PATH,
    ATTRIBUTE_ROOM_NUMBERS,
    ATTRIBUTE_ROOMS,
    ATTRIBUTE_VACUUM_POSITION,
    ATTRIBUTE_VACUUM_ROOM,
    ATTRIBUTE_VACUUM_ROOM_NAME,
    ATTRIBUTE_WALLS,
    ATTRIBUTE_ZONES,
)


@callback
def exclude_attributes(hass: HomeAssistant) -> set[str]:
    """Exclude static/ unneeded attributes from being recorded in the database."""
    return {
        ATTRIBUTE_CALIBRATION,
        ATTRIBUTE_CARPET_MAP,
        ATTRIBUTE_CHARGER,
        ATTRIBUTE_CLEANED_ROOMS,
        ATTRIBUTE_GOTO,
        ATTRIBUTE_GOTO_PATH,
        ATTRIBUTE_GOTO_PREDICTED_PATH,
        ATTRIBUTE_IGNORED_OBSTACLES,
        ATTRIBUTE_IGNORED_OBSTACLES_WITH_PHOTO,
        ATTRIBUTE_IMAGE,
        ATTRIBUTE_IS_EMPTY,
        ATTRIBUTE_MAP_NAME,
        ATTRIBUTE_MOP_PATH,
        ATTRIBUTE_NO_CARPET_AREAS,
        ATTRIBUTE_NO_GO_AREAS,
        ATTRIBUTE_NO_MOPPING_AREAS,
        ATTRIBUTE_OBSTACLES,
        ATTRIBUTE_OBSTACLES_WITH_PHOTO,
        ATTRIBUTE_PATH,
        ATTRIBUTE_ROOM_NUMBERS,
        ATTRIBUTE_ROOMS,
        ATTRIBUTE_VACUUM_POSITION,
        ATTRIBUTE_VACUUM_ROOM,
        ATTRIBUTE_VACUUM_ROOM_NAME,
        ATTRIBUTE_WALLS,
        ATTRIBUTE_ZONES,
        ATTR_BATTERY_ICON,
    }
